[VDO-5698] Ingest commits: switch logger namespace from uds to vdo
dm-vdo/vdo-devel pull request #112
Opened 2024-03-01 21:22 UTC by C2Redhat

This changes contains two commits.  

The first commit is to ingest changes from Mike Snitzer,  "dm vdo logger: change from uds_ to vdo_ namespace".  
The second commit is to adapt changes from Mike's commit.  Also, update our internal codes from uds to vdo namespaces to match the kernel changes.

2024-03-01 22:07 UTC, raeburn approved these changes

2024-03-01 22:14 UTC, lorelei-sakai requested changes
Just a few small issues.

Also, in the first commit message, please remove the line about permassert renames since that isn't in this change any more.

2024-03-01 22:14 UTC, lorelei-sakai commented on src/c++/uds/kernelLinux/uds/uds-module.c
>  EXPORT_SYMBOL_GPL(vdo_perform_once);
vdo_log_backtrace shoud go before vdo_make_funnel_queue.

2024-03-01 22:14 UTC, lorelei-sakai commented on src/c++/uds/userLinux/uds/logger.c
>  		errno = 0;
Don't change the error code here. The right check is probably "!= 0" but it's not related to this commit at any rate.

2024-03-01 22:35 UTC, lorelei-sakai approved these changes
Looks good then,

2024-03-02 00:37 UTC, lorelei-sakai approved these changes
Looks good.

2024-03-02 01:54 UTC, merged