dm vdo: Restyle function declarations and definition headers to align with dm code style.
dm-vdo/vdo-devel pull request #14
Opened 2023-10-05 19:09 UTC by raeburn

2023-10-09 07:30 UTC, raeburn commented
Per Matt's request, hold off on this untli some overlapping changes of his are committed

2023-11-08 07:09 UTC, lorelei-sakai requested changes
Wow I had a whole comment in here I lost. I'll just say, 211 comments, but only about four or five classes of common things, which we mostly talked about. There are enough brace and newline issues that I noticed that I'll put out another commit supplemental to my earlier one rather than try to absorb all those thing here.

Please especially note the comments where Mike's proposed changes differ from yours. I am very sorry this has turned into so much work.

2023-11-08 07:09 UTC, lorelei-sakai commented on src/c++/uds/src/uds/volume.c
>  			  geometry->index_pages_per_chapter);
This wrapping is actively worse. Please revert.

2023-11-08 07:09 UTC, lorelei-sakai commented on src/c++/uds/src/uds/volume.c
>  			VOLUME_CACHE_MAX_ENTRIES);
Flowing this 1/1/2 so the format string is by itself would be clearer.

2023-11-08 07:09 UTC, lorelei-sakai commented on src/c++/uds/src/uds/volume.h
Though not technically too long, I think looks better flowed 1/1/1.

2023-11-08 07:09 UTC, lorelei-sakai commented on src/c++/uds/src/uds/volume.h
nearly too long. Would look better at 2/2.

2023-11-08 14:53 UTC, lorelei-sakai commented on src/c++/vdo/base/block-map.c
[stolen]

2023-11-08 22:51 UTC, lorelei-sakai commented on src/c++/vdo/base/data-vio.c
>  	}
Putting a flag here so I remember to look at it again. This is the place where braces need to go away, now that the block is just a single line.

2023-11-10 00:30 UTC, lorelei-sakai commented on src/c++/vdo/base/slab-depot.c
>   *
This is an unrelated thing I'd like you to roll in. Coud you fix the doc for get_block_allocator_statistics() to match upstream? That is, newline after "allocators" (not before), and align the second line correctly?

This is a place where somehow vdo-devel is out of step with our upstream baseline, I'd like to align them again.

2023-11-11 01:58 UTC, lorelei-sakai approved these changes
It's been a long road, But this all looks good to me now.

2023-11-11 06:28 UTC, merged