[VDO-5576] Shut down NFS server after stopping export.
dm-vdo/vdo-devel pull request #142
Opened 2024-05-03 23:02 UTC by raeburn

The NFS server appears to hold on to references to some files for a bit otherwise.

Also, assume "systemctl" support and drop "service" path.

2024-05-03 23:08 UTC, lorelei-sakai approved these changes
I wonder if all our lab machines now have systemctl support? It doesn't look like there' any reason to merge this fix back to older branches, though, so it doesn't really matter.

2024-05-03 23:10 UTC, raeburn commented
> I wonder if all our lab machines now have systemctl support? It doesn't look like there' any reason to merge this fix back to older branches, though, so it doesn't really matter.

I checked Fedora 38 and RHEL 8 and they have systemctl, so I think we're okay.

2024-05-03 23:11 UTC, lorelei-sakai requested changes
Oh, wait. shouldn't the nfs server shutdown happen in the unexport() function instead of the unmount one?

I'm wondering what happens in the filesystem was not exported in the first place.

2024-05-08 19:38 UTC, lorelei-sakai approved these changes
Looks god to me. Yay.

2024-05-09 02:59 UTC, merged