dm vdo: adjust USE_VDO_NEXT kernel release number comparison
dm-vdo/vdo-devel pull request #186
Opened 2024-08-19 18:16 UTC by C2Redhat

Kernel release has changed from 6.9 to 6.10.  However min_heap code has not been imported to 6.10 yet. We need to adjust USE_VDO_NEXT comparison from 10 to 11 to adopt this version change.

2024-08-19 18:31 UTC, raeburn approved these changes

2024-08-19 22:09 UTC, lorelei-sakai requested changes
Can't you spell this with just one clause?

2024-08-19 22:09 UTC, lorelei-sakai commented on src/c++/vdo/base/repair.c
>  #define VDO_USE_NEXT
Can you really not spell this as (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 11, 0))?
You could also spell it as !(LINUX_VERSION_CODE < KERNEL_VERSION(6, 11, 0)).
It shouldn't need two clauses, though.

2024-08-20 14:42 UTC, lorelei-sakai approved these changes
Thank you for these changes.

2024-08-20 16:01 UTC, merged