[VDO-5862] dm vdo test: exclude Create03 test
dm-vdo/vdo-devel pull request #221
Opened 2024-12-09 20:42 UTC by C2Redhat

Create03 uses sysfs but the upstream kernel module does not load sysfs so this test will fail.  Exclude Create03 test with the --exclude flag during VDO_Upstream_Tests.

2024-12-09 20:58 UTC, lorelei-sakai requested changes
I do not tthink this i the right approach. The sysfs operations will fail on any test run with an upstream kernel, including mainlin-next and rawhide.

Instead of this, we should update the listin the "pstreamTests" suire to exclude Create03. This is the reason we created a named suite in the first place: so that we had a list that could be changed as required.

2024-12-09 21:08 UTC, C2Redhat commented
> I do not tthink this i the right approach. The sysfs operations will fail on any test run with an upstream kernel, including mainlin-next and rawhide.
> 
> Instead of this, we should update the listin the "pstreamTests" suire to exclude Create03. This is the reason we created a named suite in the first place: so that we had a list that could be changed as required.

I choose this approach since Bruce is working on disable sysfs.  We are not seeing the same problem in RAWHIDE test.  This only happen in FEDORANEXT system using --useUpstreamModule.

2024-12-09 21:25 UTC, lorelei-sakai commented
I think it is worth clarifying that even if you only want to exclude this test from one suite, the right approach is to make a new named suite and use that. The --exclude option is intended for interactive use (i.e., developers running tests directly), and should never be used in our automation.  Define a vdotests suite that includes the tests we want to run, and use that instead.

2024-12-09 21:45 UTC, C2Redhat commented
> I think it is worth clarifying that even if you only want to exclude this test from one suite, the right approach is to make a new named suite and use that. The --exclude option is intended for interactive use (i.e., developers running tests directly), and should never be used in our automation. Define a vdotests suite that includes the tests we want to run, and use that instead.

OK.  Since rawhide and upstream test are using the same suite, I think the best way is to create a new suite for upstream kernel test.  Do you have objection on this approach?

2024-12-10 18:02 UTC, lorelei-sakai approved these changes
Looks good.

2024-12-10 19:47 UTC, merged