Reflow function calls
dm-vdo/vdo-devel pull request #26
Opened 2023-10-30 23:51 UTC by raeburn

(dependent on PR#14, for the elisp code if nothing else)

2023-10-31 01:45 UTC, lorelei-sakai requested changes
Is there a good reason to have four commits for the elisp code? I could see two, maybe, for the signature work versus the fuction call work.

2023-10-31 02:05 UTC, lorelei-sakai requested changes
Generic comments that don't relate to specific code lines:

The elisp code probably doesn't need to be four separate commits (though I'm not well suited to review it anyway).

Since these patches are (mostly) going upstream, they should include a Signed-off-by: tag from you (commit -s will add that line automatically, though I haven't figured out how to 
do it after he commit is created.) We can add the tag a the later stage but it's probably good to get in the habit.

I would prefer not to say these changes are automated, at least in the commit messages for upstream. Upstream can't see the automation and if they care at all it'll most likely make them unhappy. (You can always put information like that in the PR header/merge commit message since those won't go upstream.)

Merging the two change to each code file together will probably make it a bit easier to read (or at least shorter). That should be easy enough with a rebase and reorder.

2023-11-03 20:41 UTC, raeburn commented on src/c++/uds/src/uds/chapter-index.h
>  						  u32 *lists_packed);
Putting lists_packed on the same line as last_page takes it out to 85 columns, and I was aiming for under 80.

2023-11-03 20:42 UTC, raeburn commented on src/c++/uds/src/uds/chapter-index.c
> +							      &entry);
Again, it's because the target was under 80 columns. As discussed, I'm redoing this work for 90 columns.

2023-11-03 20:43 UTC, raeburn commented on src/c++/uds/src/uds/delta-index.c
> +								 i + 1))
Yes, that's the problem with only processing function calls. I patched up several cases by hand but missed this one.

2023-11-03 20:57 UTC, sweettea commented
> Since these patches are (mostly) going upstream, they should include a 
> Signed-off-by: tag from you (commit -s will add that line 
> automatically, though I haven't figured out how to do it after he 
> commit is created.)

git commit --amend -s

> Message ID: ***@***.***>

2023-11-07 04:29 UTC, raeburn commented
subsumed into PR#14

2023-11-07 04:29 UTC, closed without merging