Fix small nits
dm-vdo/vdo-devel pull request #73
Opened 2024-01-25 19:07 UTC by C2Redhat

Implemented three Mike Snotzer's patches:

dm vdo index: fix various small nits
dm vdo dedupe: fix various small nits
dm vdo slab-depot: fix various small nits

2024-01-25 20:01 UTC, raeburn approved these changes

2024-01-25 21:29 UTC, lorelei-sakai requested changes
These changes are a little different than Mike's changes in a few spots that I've commented. Not sure how that happened.

2024-01-25 21:29 UTC, lorelei-sakai commented on src/c++/vdo/base/dedupe.c
>  	/* If there are any waiters, we need to start deduping them. */
You removed a blank line here that Mike didn't.

2024-01-25 21:29 UTC, lorelei-sakai commented on src/c++/uds/src/uds/index-session.c
>  	/* Wait for any current index state change to complete. */
I can't figure out how to make a note there, but dit looks like Mike's change had a change around line 394 of index-session.c that got completely dropped.

2024-01-26 00:52 UTC, lorelei-sakai approved these changes
Looks good now.

2024-01-26 01:03 UTC, merged